# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVP
  
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'MessageKit'
  pod 'SDWebImage'

end
